title: 1kB Club
description: An exclusive membership for web pages weighing less than 1 kilobyte.
baseurl: '' # the subpath of your site, e.g. /blog
url: https://1kb.club # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Bradley Taunt
  email: hello@tdarb.org

# Collections
collections:
  site_listings:
    output: false
  u:
    output: true

permalink: /blog/:title/

highlighter: none

compress_html:
  clippings: all
  endings: all
  startings: [html, head, body]

exclude:
  - generate.sh
  - README.md

include:
  - netlify.toml
  - ~/
